### ISSUE TITLE
Duplicated viewport meta element

### ISSUE THREAD

**Issue by samwilson** [carew/theme-bootstrap#3]
This may well be intentional and a workaround for some obscure browser issue, but the `viewport` meta element is duplicated in `layouts/default.html.twig`:

```html
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="viewport" content="width=device-width">
```

**Comment by lyrixx** [comment]
Indeed, this is a bug. Can you submit a pull request ?
